add_test( [==[Number Expression]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Number Expression]==]  )
set_tests_properties( [==[Number Expression]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Boolean Expression]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Boolean Expression]==]  )
set_tests_properties( [==[Boolean Expression]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Variable Expression]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Variable Expression]==]  )
set_tests_properties( [==[Variable Expression]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Function Call]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Function Call]==]  )
set_tests_properties( [==[Function Call]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Parse Error]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Parse Error]==]  )
set_tests_properties( [==[Parse Error]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Division by Zero]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Division by Zero]==]  )
set_tests_properties( [==[Division by Zero]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[New Boolean Operators]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[New Boolean Operators]==]  )
set_tests_properties( [==[New Boolean Operators]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Equality Operators]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Equality Operators]==]  )
set_tests_properties( [==[Equality Operators]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Extended Comparison Operators]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Extended Comparison Operators]==]  )
set_tests_properties( [==[Extended Comparison Operators]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Complex Expressions]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Complex Expressions]==]  )
set_tests_properties( [==[Complex Expressions]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Unary Operators]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Unary Operators]==]  )
set_tests_properties( [==[Unary Operators]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Parentheses and Complex Arithmetic]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Parentheses and Complex Arithmetic]==]  )
set_tests_properties( [==[Parentheses and Complex Arithmetic]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Variables in Complex Expressions]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Variables in Complex Expressions]==]  )
set_tests_properties( [==[Variables in Complex Expressions]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Real World Scenarios]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Real World Scenarios]==]  )
set_tests_properties( [==[Real World Scenarios]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Complex Boolean Logic]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Complex Boolean Logic]==]  )
set_tests_properties( [==[Complex Boolean Logic]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Mixed Type Expressions]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Mixed Type Expressions]==]  )
set_tests_properties( [==[Mixed Type Expressions]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Edge Cases and Error Handling]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Edge Cases and Error Handling]==]  )
set_tests_properties( [==[Edge Cases and Error Handling]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( Backends /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest Backends  )
set_tests_properties( Backends PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
add_test( [==[Standard Mathematical Functions]==] /home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest [==[Standard Mathematical Functions]==]  )
set_tests_properties( [==[Standard Mathematical Functions]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/ExpressionKit/ExpressionKit)
set( ExprTKTest_TESTS [==[Number Expression]==] [==[Boolean Expression]==] [==[Variable Expression]==] [==[Function Call]==] [==[Parse Error]==] [==[Division by Zero]==] [==[New Boolean Operators]==] [==[Equality Operators]==] [==[Extended Comparison Operators]==] [==[Complex Expressions]==] [==[Unary Operators]==] [==[Parentheses and Complex Arithmetic]==] [==[Variables in Complex Expressions]==] [==[Real World Scenarios]==] [==[Complex Boolean Logic]==] [==[Mixed Type Expressions]==] [==[Edge Cases and Error Handling]==] Backends [==[Standard Mathematical Functions]==])
