if(EXISTS "/home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest_tests-b12d07c.cmake")
  include("/home/runner/work/ExpressionKit/ExpressionKit/ExprTKTest_tests-b12d07c.cmake")
else()
  add_test(ExprTKTest_NOT_BUILT-b12d07c ExprTKTest_NOT_BUILT-b12d07c)
endif()
